# Generated by Django 5.2 on 2025-04-08 08:50

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category', models.CharField(choices=[('student', 'Student'), ('professional', 'Professional')], max_length=20)),
                ('transcation_id', models.CharField(default=uuid.uuid4, editable=False, help_text='Auto _generated transaction id', max_length=200, unique=True)),
                ('organisation_name', models.CharField(blank=True, max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meals', models.CharField(choices=[('veg', 'Veg'), ('non-veg', 'Non-veg')], max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=10)),
                ('additional_comments', models.CharField(blank=True, default='none comment', max_length=500)),
                ('about_us', models.CharField(choices=[('email', 'Email'), ('website', 'Website'), ('social media', 'Social media'), ('collage', 'Collage'), ('other', 'Other')], max_length=30)),
            ],
        ),
    ]
