# Generated by Django 5.2 on 2025-04-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transcation_id',
            field=models.CharField(blank=True, editable=False, help_text='Auto _generated transaction id', max_length=200, unique=True),
        ),
    ]
