# Generated by Django 5.2 on 2025-04-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_payment_transcation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
