# Generated by Django 5.2 on 2025-04-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_payment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
