# Generated by Django 5.2 on 2025-04-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_payment_bank_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transcation_id',
            field=models.CharField(blank=True, editable=False, max_length=200),
        ),
    ]
