# Generated by Django 5.2 on 2025-04-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_payment_transcation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='additional_comments',
            field=models.CharField(blank=True, default=' ', max_length=500),
        ),
    ]
