# Generated by Django 5.2 on 2025-04-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_payment_additional_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transcation_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
